export const data = [
  {
    _id: "6544cf3122956f28dc022f3a",
    booking_id: 6064573,
    customer_name: "N K Mohanty",
    collection_date: "2023-11-03 00:00:00 UTC",
    booking_date: "2023-11-01 00:00:00 UTC",
    lead_id: 5668647,
    uhid: 5190829,
    useruuid: "98a9503a-d78f-4b8b-8543-4b55d26a4457",
    test_id: 5635,
    test_code: "PL94",
    test_name: "Liver Function Test (LFT)",
    test_values: [
      {
        test_method: "Photometric",
        test_parameter_id: 7052155,
        parameter_name: "BILIRUBIN TOTAL",
        parameter_value: "0.4",
        is_highlighted: false,
        lower_bound: "0.2",
        display_value: "0.2 - 1.2",
        upper_bound: "1.2",
        impression: "N",
        unit: "mg/dL",
        "  ": "392",
      },
      {
        test_method: "Diazo Reaction",
        test_parameter_id: 9764,
        parameter_name: "BILIRUBIN DIRECT",
        parameter_value: "0.21",
        is_highlighted: false,
        lower_bound: "0",
        display_value: "0.0 - 0.5",
        upper_bound: "0.5",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "393",
      },
      {
        test_method: "Calculation (T Bil - D Bil)",
        test_parameter_id: 7049951,
        parameter_name: "BILIRUBIN INDIRECT",
        parameter_value: "0.19",
        is_highlighted: false,
        lower_bound: "0.1",
        display_value: "0.1 - 1.0",
        upper_bound: "1",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "394",
      },
      {
        test_method: "IFCC without P5P",
        test_parameter_id: 704366,
        parameter_name: "SGOT/AST",
        parameter_value: "19.9",
        is_highlighted: false,
        lower_bound: "5",
        display_value: "5 - 34",
        upper_bound: "34",
        impression: "N",
        unit: "U/L",
        other_male_id: "413",
      },
      {
        test_method: "IFCC without P5P",
        test_parameter_id: 7050593,
        parameter_name: "SGPT/ALT",
        parameter_value: "18.4",
        is_highlighted: false,
        lower_bound: "0",
        display_value: "0 to 55",
        upper_bound: "55",
        impression: "N",
        unit: "U/L",
        other_male_id: "414",
      },
      {
        test_method: "",
        test_parameter_id: 7049952,
        parameter_name: "SGOT/SGPT Ratio",
        parameter_value: "1.08",
        is_highlighted: false,
        lower_bound: "",
        display_value: "-",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "415",
      },
      {
        test_method: "IFCC",
        test_parameter_id: 72706,
        parameter_name: "ALKALINE PHOSPHATASE",
        parameter_value: "67",
        is_highlighted: false,
        lower_bound: "40",
        display_value: "40 - 150",
        upper_bound: "150",
        impression: "N",
        unit: "U/L",
        other_male_id: "15",
      },
      {
        test_method: "Biuret",
        test_parameter_id: 7049780,
        parameter_name: "TOTAL PROTEIN",
        parameter_value: "6.5",
        is_highlighted: false,
        lower_bound: "6.4",
        display_value: "6.4  -  8.3",
        upper_bound: "8.3",
        impression: "N",
        unit: "g/dL",
        other_male_id: "35",
      },
      {
        test_method: "BCG",
        test_parameter_id: 704371,
        parameter_name: "ALBUMIN",
        parameter_value: "4",
        is_highlighted: false,
        lower_bound: "3.8",
        display_value: "3.8  -  5.0",
        upper_bound: "5",
        impression: "N",
        unit: "gm/dL",
        other_male_id: "36",
      },
      {
        test_method: "Calculation (T.P - Albumin)",
        test_parameter_id: 2779,
        parameter_name: "GLOBULIN",
        parameter_value: "2.5",
        is_highlighted: false,
        lower_bound: "2.3",
        display_value: "2.3 - 3.5",
        upper_bound: "3.5",
        impression: "N",
        unit: "g/dL",
        other_male_id: "416",
      },
      {
        test_method: "Calculation (Albumin/Globulin)",
        test_parameter_id: 2780,
        parameter_name: "ALBUMIN : GLOBULIN RATIO",
        parameter_value: "1.6",
        is_highlighted: false,
        lower_bound: "1",
        display_value: "1.0 - 2.1<br />",
        upper_bound: "2.1",
        impression: "N",
        unit: "-",
        other_male_id: "417",
      },
      {
        test_method: "ENZYMATIC",
        test_parameter_id: 170174,
        parameter_name: "GAMMA GLUTAMYL TRANSFERASE (GGT)",
        parameter_value: "19.4",
        is_highlighted: false,
        lower_bound: "0",
        display_value: "0 - 55",
        upper_bound: "55",
        impression: "N",
        unit: "U/L",
        other_male_id: "37",
      },
    ],
    created_at: "2023-11-03 10:45:05.245 UTC",
    updated_at: "2023-11-03 10:45:05.245 UTC",
    __hevo_id:
      "602497ff3fdeb3d633a29d791cbe653ce7c54ded63fd9ec57452661240521533",
    __hevo__ingested_at: 1699008614494,
    __hevo__loaded_at: 1699021932207,
    __hevo__marked_deleted: false,
    __hevo__source_modified_at: 1699008305000,
  },
  {
    _id: "6544cf2e3e35f66b496a370d",
    booking_id: 6064573,
    customer_name: "N K Mohanty",
    collection_date: "2023-11-03 00:00:00 UTC",
    booking_date: "2023-11-01 00:00:00 UTC",
    lead_id: 5668647,
    uhid: 5190829,
    useruuid: "98a9503a-d78f-4b8b-8543-4b55d26a4457",
    test_id: 5614,
    test_code: "BC023",
    test_name: "Glucose Fasting (BSF)",
    test_values: [
      {
        test_method: "Hexokinase",
        test_parameter_id: 7052221,
        parameter_name: "GLUCOSE FASTING",
        parameter_value: "85.2",
        is_highlighted: false,
        lower_bound: "70",
        display_value: "70 - 100",
        upper_bound: "100",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "441",
      },
    ],
    created_at: "2023-11-03 10:45:02.733 UTC",
    updated_at: "2023-11-03 10:45:02.733 UTC",
    __hevo_id:
      "989b20ece0de8d82d5ed609f7cc1704cc4a00446f6f2583078c000af06e1d212",
    __hevo__ingested_at: 1699008614494,
    __hevo__loaded_at: 1699021932207,
    __hevo__marked_deleted: false,
    __hevo__source_modified_at: 1699008302000,
  },
  {
    _id: "6544cf3122956f28dc022f39",
    booking_id: 6064573,
    customer_name: "N K Mohanty",
    collection_date: "2023-11-03 00:00:00 UTC",
    booking_date: "2023-11-01 00:00:00 UTC",
    lead_id: 5668647,
    uhid: 5190829,
    useruuid: "98a9503a-d78f-4b8b-8543-4b55d26a4457",
    test_id: 5684,
    test_code: "CP012",
    test_name: "Urine Routine and Microscopic Examination",
    test_values: [
      {
        test_method: "",
        test_parameter_id: 7049809,
        parameter_name: "PHYSICAL EXAMINATON",
        parameter_value: "HEAD",
        is_highlighted: false,
        lower_bound: "",
        display_value: "",
        upper_bound: "",
        impression: "N",
        unit: "",
        other_male_id: "654",
      },
      {
        test_method: "",
        test_parameter_id: 7050015,
        parameter_name: "Volume",
        parameter_value: "5",
        is_highlighted: false,
        lower_bound: "",
        display_value: "-",
        upper_bound: "",
        impression: "N",
        unit: "mL",
        other_male_id: "111",
      },
      {
        test_method: "",
        test_parameter_id: 7020153,
        parameter_name: "Colour",
        parameter_value: "Pale yellow",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Pale yellow",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "76",
      },
      {
        test_method: "",
        test_parameter_id: 7049812,
        parameter_name: "Transparency",
        parameter_value: "Clear",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Clear",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "113",
      },
      {
        test_method: "",
        test_parameter_id: 7049813,
        parameter_name: "Deposit",
        parameter_value: "Absent",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Absent",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "114",
      },
      {
        test_method: "",
        test_parameter_id: 7049814,
        parameter_name: "CHEMICAL EXAMINATION",
        parameter_value: "HEAD",
        is_highlighted: false,
        lower_bound: "",
        display_value: "",
        upper_bound: "",
        impression: "N",
        unit: "",
        other_male_id: "655",
      },
      {
        test_method: "Double Indicator",
        test_parameter_id: 7049998,
        parameter_name: "Reaction (pH)",
        parameter_value: "5.0",
        is_highlighted: false,
        lower_bound: "4.5",
        display_value: "4.5 - 8.0",
        upper_bound: "8.0",
        impression: "N",
        unit: "-",
        other_male_id: "115",
      },
      {
        test_method: "Ion Exchange",
        test_parameter_id: 7049991,
        parameter_name: "Specific Gravity",
        parameter_value: "1.015",
        is_highlighted: false,
        lower_bound: "1.010",
        display_value: "1.010 - 1.030",
        upper_bound: "1.030",
        impression: "N",
        unit: "-",
        other_male_id: "116",
      },
      {
        test_method: "",
        test_parameter_id: 7049817,
        parameter_name: "Urine Glucose (sugar)",
        parameter_value: "Negative",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Negative",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "117",
      },
      {
        test_method: "",
        test_parameter_id: 7049818,
        parameter_name: "Urine Protein (Albumin)",
        parameter_value: "Negative",
        is_highlighted: false,
        lower_bound: "-",
        display_value: "Negative",
        upper_bound: "-",
        impression: "N",
        unit: "-",
        other_male_id: "118",
      },
      {
        test_method: "",
        test_parameter_id: 7052215,
        parameter_name: "Urine Ketones (Acetone)",
        parameter_value: "Negative",
        is_highlighted: false,
        lower_bound: "-",
        display_value: "Negative",
        upper_bound: "-",
        impression: "N",
        unit: "-",
        other_male_id: "119",
      },
      {
        test_method: "",
        test_parameter_id: 7049820,
        parameter_name: "Blood",
        parameter_value: "Negative",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Negative",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "120",
      },
      {
        test_method: "",
        test_parameter_id: 7052224,
        parameter_name: "Leucocyte  esterase",
        parameter_value: "Negative",
        is_highlighted: false,
        lower_bound: "-",
        display_value: "Negative",
        upper_bound: "-",
        impression: "N",
        unit: "-",
        other_male_id: "121",
      },
      {
        test_method: "",
        test_parameter_id: 7049821,
        parameter_name: "Bilirubin Urine",
        parameter_value: "Negative",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Negative",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "672",
      },
      {
        test_method: "Griless Test",
        test_parameter_id: 7049822,
        parameter_name: "Nitrite",
        parameter_value: "Negative",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Negative",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "122",
      },
      {
        test_method: "Ehrlichs Test",
        test_parameter_id: 7049823,
        parameter_name: "Urobilinogen",
        parameter_value: "Normal",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Normal",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "123",
      },
      {
        test_method: "",
        test_parameter_id: 7049824,
        parameter_name: "MICROSCOPIC EXAMINATION",
        parameter_value: "HEAD",
        is_highlighted: false,
        lower_bound: "",
        display_value: "",
        upper_bound: "",
        impression: "N",
        unit: "",
        other_male_id: "656",
      },
      {
        test_method: "",
        test_parameter_id: 7049825,
        parameter_name: "Pus Cells (WBCs)",
        parameter_value: "1-2",
        is_highlighted: false,
        lower_bound: "0",
        display_value: "0 - 5",
        upper_bound: "5",
        impression: "N",
        unit: "/hpf",
        other_male_id: "124",
      },
      {
        test_method: "",
        test_parameter_id: 7050018,
        parameter_name: "Epithelial Cells",
        parameter_value: "1-2",
        is_highlighted: false,
        lower_bound: "0",
        display_value: "0 - 4",
        upper_bound: "4",
        impression: "N",
        unit: "/hpf",
        other_male_id: "125",
      },
      {
        test_method: "",
        test_parameter_id: 7051959,
        parameter_name: "Red blood Cells",
        parameter_value: "Absent",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Absent",
        upper_bound: "",
        impression: "N",
        unit: "/hpf",
        other_male_id: "126",
      },
      {
        test_method: "",
        test_parameter_id: 7049828,
        parameter_name: "Crystals",
        parameter_value: "Absent",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Absent",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "127",
      },
      {
        test_method: "",
        test_parameter_id: 7049829,
        parameter_name: "Cast",
        parameter_value: "Absent",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Absent",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "128",
      },
      {
        test_method: "",
        test_parameter_id: 7049830,
        parameter_name: "Yeast Cells",
        parameter_value: "Absent",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Absent",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "129",
      },
      {
        test_method: "",
        test_parameter_id: 7049831,
        parameter_name: "Amorphous deposits",
        parameter_value: "Absent",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Absent",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "130",
      },
      {
        test_method: "",
        test_parameter_id: 7049832,
        parameter_name: "Bacteria",
        parameter_value: "Absent",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Absent",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "131",
      },
      {
        test_method: "",
        test_parameter_id: 2858,
        parameter_name: "Protozoa",
        parameter_value: "Absent",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Absent",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "673",
      },
    ],
    created_at: "2023-11-03 10:45:04.91 UTC",
    updated_at: "2023-11-03 10:45:04.91 UTC",
    __hevo_id:
      "99f97a27415c56cc1bcdb955939f63e6d46c0246869b90a02b0f369f68ad4eed",
    __hevo__ingested_at: 1699008614494,
    __hevo__loaded_at: 1699021932207,
    __hevo__marked_deleted: false,
    __hevo__source_modified_at: 1699008305000,
  },
  {
    _id: "6544cf2f42476de9455ec6fc",
    booking_id: 6064573,
    customer_name: "N K Mohanty",
    collection_date: "2023-11-03 00:00:00 UTC",
    booking_date: "2023-11-01 00:00:00 UTC",
    lead_id: 5668647,
    uhid: 5190829,
    useruuid: "98a9503a-d78f-4b8b-8543-4b55d26a4457",
    test_id: 5618,
    test_code: "BC035",
    test_name: "HbA1C (Glycosylated Haemoglobin)",
    test_values: [
      {
        test_method: "HPLC",
        test_parameter_id: 7051016,
        parameter_name: "GLYCOSYLATED HEMOGLOBIN (HbA1c)",
        parameter_value: "5.9",
        is_highlighted: true,
        lower_bound: "0",
        display_value: "< 5.7",
        upper_bound: "5.6",
        impression: "H",
        unit: "%",
        other_male_id: "438",
      },
      {
        test_method: "",
        test_parameter_id: 7052039,
        parameter_name: "ESTIMATED AVERAGE GLUCOSE",
        parameter_value: "122.63",
        is_highlighted: false,
        lower_bound: "",
        display_value: "Refer Table Below",
        upper_bound: "",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "439",
      },
    ],
    created_at: "2023-11-03 10:45:03.447 UTC",
    updated_at: "2023-11-03 10:45:03.447 UTC",
    __hevo_id:
      "1e97728f32d2f339aa40c2f23f57a241e15eeb4cabbe39da94d847dd51eea975",
    __hevo__ingested_at: 1699008614494,
    __hevo__loaded_at: 1699021932207,
    __hevo__marked_deleted: false,
    __hevo__source_modified_at: 1699008303000,
  },
  {
    _id: "6544cf321b9820ff812d1812",
    booking_id: 6064573,
    customer_name: "N K Mohanty",
    collection_date: "2023-11-03 00:00:00 UTC",
    booking_date: "2023-11-01 00:00:00 UTC",
    lead_id: 5668647,
    uhid: 5190829,
    useruuid: "98a9503a-d78f-4b8b-8543-4b55d26a4457",
    test_id: 5632,
    test_code: "BC471",
    test_name: "Lipid Profile",
    test_values: [
      {
        test_method: "Enzymatic - Cholesterol Oxidase",
        test_parameter_id: 7050994,
        parameter_name: "TOTAL CHOLESTEROL",
        parameter_value: "164",
        is_highlighted: false,
        lower_bound: "0",
        display_value:
          "Desirable :    <200<br />Borderline :  200-239<br />High :         >240",
        upper_bound: "200",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "424",
      },
      {
        test_method: "Colorimetric - Lip/Glycerol Kinase",
        test_parameter_id: 7052228,
        parameter_name: "TRIGLYCERIDES",
        parameter_value: "85.9",
        is_highlighted: false,
        lower_bound: "0",
        display_value:
          "Normal :           <150<br />Borderline :      150-199<br />High :            200-499<br />Very high :        >500",
        upper_bound: "150",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "425",
      },
      {
        test_method: "Accelerator Selective Detergent",
        test_parameter_id: 7050643,
        parameter_name: "HDL CHOLESTEROL",
        parameter_value: "48.6",
        is_highlighted: false,
        lower_bound: "",
        display_value: ">40",
        upper_bound: "",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "426",
      },
      {
        test_method: "Calculated",
        test_parameter_id: 7050418,
        parameter_name: "NON HDL CHOLESTEROL",
        parameter_value: "115.4",
        is_highlighted: false,
        lower_bound: "0",
        display_value: "<130",
        upper_bound: "130",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "443",
      },
      {
        test_method: "Calculated",
        test_parameter_id: 7050871,
        parameter_name: "LDL CHOLESTEROL",
        parameter_value: "98.22",
        is_highlighted: false,
        lower_bound: "30",
        display_value:
          "Optimalt                        <100 <br />Near optimal/above optimal     100-129 Borderline hight               130-159<br />Hight                       160-189<br />Very hight                >190",
        upper_bound: "129",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "427",
      },
      {
        test_method: "Calculated",
        test_parameter_id: 7049941,
        parameter_name: "V.L.D.L CHOLESTEROL",
        parameter_value: "17.18",
        is_highlighted: false,
        lower_bound: "0",
        display_value: "&lt; 30",
        upper_bound: "30",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "428",
      },
      {
        test_method: "Calculated",
        test_parameter_id: 7050421,
        parameter_name: "CHOL/HDL Ratio",
        parameter_value: "3.37",
        is_highlighted: true,
        lower_bound: "3.5",
        display_value: "3.5 - 5.0",
        upper_bound: "5",
        impression: "L",
        unit: "-",
        other_male_id: "445",
      },
      {
        test_method: "Calculated",
        test_parameter_id: 17367,
        parameter_name: "HDL/ LDL RATIO",
        parameter_value: "0.49",
        is_highlighted: false,
        lower_bound: "-",
        display_value:
          "Desirable : 0.5 - 3.0<br /><br />Borderline : 3.1 - 6.0<br /><br />High : &gt; 6.0",
        upper_bound: "-",
        impression: "N",
        unit: "-",
        other_male_id: "446",
      },
      {
        test_method: "Calculated",
        test_parameter_id: 17368,
        parameter_name: "LDL/HDL Ratio",
        parameter_value: "2.02",
        is_highlighted: false,
        lower_bound: "",
        display_value: "",
        upper_bound: "",
        impression: "N",
        unit: "-",
        other_male_id: "447",
      },
    ],
    created_at: "2023-11-03 10:45:05.998 UTC",
    updated_at: "2023-11-03 10:45:05.998 UTC",
    __hevo_id:
      "e479c5c090e81fc778b08b7325719499be78e6d57066e57f16bae7003736fd3b",
    __hevo__ingested_at: 1699008614494,
    __hevo__loaded_at: 1699021932207,
    __hevo__marked_deleted: false,
    __hevo__source_modified_at: 1699008306000,
  },
  {
    _id: "6544cf3042476de9455ec701",
    booking_id: 6064573,
    customer_name: "N K Mohanty",
    collection_date: "2023-11-03 00:00:00 UTC",
    booking_date: "2023-11-01 00:00:00 UTC",
    lead_id: 5668647,
    uhid: 5190829,
    useruuid: "98a9503a-d78f-4b8b-8543-4b55d26a4457",
    test_id: 5667,
    test_code: "BC063",
    test_name: "Thyroid Profile Total",
    test_values: [
      {
        test_method: "ECLIA",
        test_parameter_id: 7050768,
        parameter_name: "TRIIODOTHYRONINE ( T3 )",
        parameter_value: "118.9",
        is_highlighted: false,
        lower_bound: "80",
        display_value: "80 -200",
        upper_bound: "200",
        impression: "N",
        unit: "ng/dL",
        other_male_id: "44",
      },
      {
        test_method: "ECLIA",
        test_parameter_id: 7050769,
        parameter_name: "TOTAL THYROXINE ( T4 )",
        parameter_value: "9.44",
        is_highlighted: false,
        lower_bound: "5.1",
        display_value: "5.1 - 14.1",
        upper_bound: "14.1",
        impression: "N",
        unit: "g/dL",
        other_male_id: "4",
      },
      {
        test_method: "Chemiluminescence Immuno Assay (CLIA)",
        test_parameter_id: 7052387,
        parameter_name: "THYROID STIMULATING HORMONE  (Ultrasensitive)",
        parameter_value: "7.59",
        is_highlighted: true,
        lower_bound: "0.4",
        display_value: "0.4  -  4.2",
        upper_bound: "4.2",
        impression: "H",
        unit: "µIU/mL",
        other_male_id: "41",
      },
    ],
    created_at: "2023-11-03 10:45:04.157 UTC",
    updated_at: "2023-11-03 10:45:04.157 UTC",
    __hevo_id:
      "970301925251d0a46a5044ecc528ba07375f763fbe72b05bc710a35b5af4553b",
    __hevo__ingested_at: 1699008614494,
    __hevo__loaded_at: 1699021932207,
    __hevo__marked_deleted: false,
    __hevo__source_modified_at: 1699008304000,
  },
  {
    _id: "6544cf2f9372785fe17c6d01",
    booking_id: 6064573,
    customer_name: "N K Mohanty",
    collection_date: "2023-11-03 00:00:00 UTC",
    booking_date: "2023-11-01 00:00:00 UTC",
    lead_id: 5668647,
    uhid: 5190829,
    useruuid: "98a9503a-d78f-4b8b-8543-4b55d26a4457",
    test_id: 5628,
    test_code: "BC360",
    test_name: "Kidney Function Test (KFT)",
    test_values: [
      {
        test_method: "Urease",
        test_parameter_id: 5100,
        parameter_name: "BLOOD UREA",
        parameter_value: "12.9",
        is_highlighted: true,
        lower_bound: "18",
        display_value: "18 - 55",
        upper_bound: "55",
        impression: "L",
        unit: "mg/dL",
        other_male_id: "448",
      },
      {
        test_method: "Photometric",
        test_parameter_id: 7052160,
        parameter_name: "CREATININE",
        parameter_value: "0.8",
        is_highlighted: false,
        lower_bound: "0.72",
        display_value: "0.72 - 1.25",
        upper_bound: "1.25",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "85",
      },
      {
        test_method: "Urease",
        test_parameter_id: 5102,
        parameter_name: "BUN",
        parameter_value: "6.03",
        is_highlighted: true,
        lower_bound: "8.4",
        display_value: "8.4 - 25.7",
        upper_bound: "25.7",
        impression: "L",
        unit: "mg/dL",
        other_male_id: "154",
      },
      {
        test_method: "",
        test_parameter_id: 7049764,
        parameter_name: "BUN/CREATININE RATIO",
        parameter_value: "7.54",
        is_highlighted: false,
        lower_bound: "",
        display_value: "",
        upper_bound: "",
        impression: "N",
        unit: "",
        other_male_id: "450",
      },
      {
        test_method: "",
        test_parameter_id: 7052037,
        parameter_name: "UREA / CREATININE RATIO",
        parameter_value: "16.13",
        is_highlighted: false,
        lower_bound: "",
        display_value: "",
        upper_bound: "",
        impression: "N",
        unit: "",
        other_male_id: "927",
      },
      {
        test_method: "Uricase",
        test_parameter_id: 7052223,
        parameter_name: "URIC ACID",
        parameter_value: "7",
        is_highlighted: false,
        lower_bound: "3.5",
        display_value: "3.5 - 7.2",
        upper_bound: "7.2",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "449",
      },
      {
        test_method: "Arsenazo III",
        test_parameter_id: 704380,
        parameter_name: "CALCIUM Serum",
        parameter_value: "8.5",
        is_highlighted: false,
        lower_bound: "8.4",
        display_value: "8.4 - 10.2",
        upper_bound: "10.2",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "16",
      },
      {
        test_method: "Photometric",
        test_parameter_id: 7049766,
        parameter_name: "PHOSPHORUS",
        parameter_value: "3.8",
        is_highlighted: false,
        lower_bound: "2.3",
        display_value: "2.3 - 4.7",
        upper_bound: "4.7",
        impression: "N",
        unit: "mg/dL",
        other_male_id: "47",
      },
      {
        test_method: "Potentiometric",
        test_parameter_id: 7049767,
        parameter_name: "SODIUM",
        parameter_value: "137.5",
        is_highlighted: false,
        lower_bound: "136",
        display_value: "136 - 145",
        upper_bound: "145",
        impression: "N",
        unit: "mmol/L",
        other_male_id: "51",
      },
      {
        test_method: "Potentiometric",
        test_parameter_id: 7051486,
        parameter_name: "POTASSIUM",
        parameter_value: "3.7",
        is_highlighted: false,
        lower_bound: "3.5",
        display_value: "3.5 - 5.1",
        upper_bound: "5.1",
        impression: "N",
        unit: "mmol/L",
        other_male_id: "32",
      },
      {
        test_method: "Photometric",
        test_parameter_id: 7051776,
        parameter_name: "CHLORIDE",
        parameter_value: "104.2",
        is_highlighted: false,
        lower_bound: "98",
        display_value: "98 - 107",
        upper_bound: "107",
        impression: "N",
        unit: "mmol/L",
        other_male_id: "177",
      },
    ],
    created_at: "2023-11-03 10:45:03.711 UTC",
    updated_at: "2023-11-03 10:45:03.711 UTC",
    __hevo_id:
      "80cf4f6983ce1c7d8906cc83083c10911cb22437675b2f9152b94609f9c561b0",
    __hevo__ingested_at: 1699008614494,
    __hevo__loaded_at: 1699021932207,
    __hevo__marked_deleted: false,
    __hevo__source_modified_at: 1699008303000,
  },
];
